FROM	debian:bullseye

RUN apt-get update
RUN apt-get install -y mariadb-server vim
# カスタムエントリポイントスクリプトをコピー
COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["mysqld_safe"]