version: '3'

services:
  nginx:
    build: ./requirements/nginx
    ports: 
      - "443:443"
    restart: always
    networks:
      - nginx
    volumes:
      - volume:/var/www/html
      - ./requirements/nginx/default:/etc/nginx/sites-available/default
    depends_on:
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    restart: always
    depends_on:
      - mariadb
    networks:
      - nginx
      - db
    volumes:
      - volume:/var/www/html
      - ./requirements/wordpress/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress_db

  mariadb:
    build: ./requirements/mariadb
    restart: always
    networks:
      - db
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    tty: true

volumes:
    volume:

networks:
    nginx: 
    db: 

