version: '3'

services:
  nginx:
    build: ./requirements/nginx
    ports: 
      - "443:443"
    restart: always
    networks:
      - nginx
    volumes:
      - wordpress:/var/www/html
      - ./requirements/nginx/default:/etc/nginx/sites-available/default
    depends_on:
      wordpress:
        condition: service_started

  wordpress:
    build: ./requirements/wordpress
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - nginx
      - db
    volumes:
      - wordpress:/var/www/html
      - ./requirements/wordpress/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
    env_file:
      - .env

  mariadb:
    build: ./requirements/mariadb
    restart: always
    networks:
      - db
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "mysql --user=user --password=password -e 'SELECT 1'"]
      interval: 3s
      timeout: 10s
      retries: 3
      start_period: 3s


volumes:
    wordpress:
    mariadb:

networks:
    nginx: 
    db:

